export const site = {
  url: "https://karimareda.vercel.app",
  name: "Karima Reda",
  email: "karimareda1247@gmail.com",
  whatsapp: "https://wa.me/201222189863",
  facebook: "https://www.facebook.com/share/1EdXmdaQNG/?mibextid=wwXIfr",
  instagram:
    "https://www.instagram.com/karima_redaa?stkn=d2h6Mzh6bTNlZ25j&utm_source=qr",
  tiktok: "https://www.tiktok.com/@karima_reda2?_r=1&_t=ZS-9ALCzk8UIVd",
  title:
    "Karima Reda | UGC Creator & Influencer in Egypt | كريمة رضا صانعة محتوى UGC",
  description:
    "Karima Reda – UGC creator & influencer in Cairo, Egypt. Authentic high-converting video content for skincare, perfume, fashion & food brands. كريمة رضا صانعة محتوى UGC ومؤثرة في القاهرة لعلامات العناية بالبشرة والعطور والأزياء والطعام.",
  keywords: [
    "UGC creator",
    "UGC creator Egypt",
    "UGC Cairo",
    "influencer Egypt",
    "content creator Cairo",
    "UGC videos",
    "product review videos",
    "skincare UGC",
    "perfume UGC",
    "fashion UGC",
    "food content creator",
    "brand ambassador Egypt",
    "unboxing videos",
    "ASMR content",
    "Reels creator",
    "صانعة محتوى",
    "صانعة محتوى UGC",
    "كريتور UGC مصر",
    "مؤثرة مصرية",
    "انفلونسر مصر",
    "محتوى فيديو للعلامات التجارية",
    "مراجعات منتجات",
    "فيديوهات UGC",
    "إعلانات UGC",
    "تسويق بالمحتوى",
    "العناية بالبشرة",
    "عطور",
    "أزياء محتشمة",
    "القاهرة",
    "ريلز",
  ],
};
